feat: instances
cognitedata/cognite-sdk-js pull request #1047
Opened 2024-01-11 10:46 UTC by gulkaktus

2024-01-15 15:00 UTC, gulkaktus commented on packages/stable/src/.cognite-openapi-snapshot.json
> -                },
Should not remove this. Was only done to make type generation script run

2024-01-17 11:41 UTC, andersfylling requested changes

2024-01-17 11:41 UTC, andersfylling commented on packages/stable/src/exports.gen.ts
> +export {
This file is owned by the codegen package. So whenever someone runs codegen, these imports will be lost.

Simply moving these out of the exports.gen.ts file will resolve the potential future issue.

2024-01-17 11:47 UTC, gulkaktus commented on packages/stable/src/exports.gen.ts
> +export {
Thanks for pointing that out! Moved the types to the types.ts file instead.

2024-01-17 12:16 UTC, andersfylling approved these changes
lgtm.

If you make any big chances, besides fixing the test cases, then please request another review.

2024-01-18 10:59 UTC, merged