fix: Fix test for pagination cursor
cognitedata/cognite-sdk-js pull request #1138
Opened 2024-08-26 10:58 UTC by VebjornG

In the previous test of the pagination cursor in alert-api, 1001 alerts was created. This created 504s, so we reduced that number to 50. 
[Ticket](https://cognitedata.atlassian.net/browse/AH-3708).

2024-08-26 11:38 UTC, BugGambit commented on packages/beta/src/__tests__/api/alertsApi.int.spec.ts
> +    expect((await alerts).length).toBe(50);
I don't understand how this tests pagination. Aren't we just fetching 50 alerts without pagination here?
Also `autoPagingToArray({ limit: 50 });` will not provide a `limit` query param to the API as this is logic for the SDK. If you want to send a `limit` query param to the API, then it should be here:
```js
const alerts = client.alerts.list({..., limit: 25})`
```

2024-08-26 11:39 UTC, BugGambit requested changes, later dismissed
Also, this is not a `fix` as specified in the PR title and commit.
From the end-users point of view, this PR doesn't fix any bugs.

The proper prefix is `test`

See the contribution docs: https://github.com/cognitedata/cognite-sdk-js/blob/master/CONTRIBUTING.md#making-changes

2024-09-04 08:48 UTC, vincent-cognite commented on packages/beta/src/__tests__/api/alertsApi.int.spec.ts
>      expect(response.items.length).toBe(1);
No alarm has been created at this point, so why is this expected?
Is it coming from a previous test?

2024-09-04 08:49 UTC, vincent-cognite approved these changes
looks like you are testing the pagination correctly. I am not sure I understand how the test is structured though...

2024-09-04 09:02 UTC, merged