fix: allow shallow copying for Asset and Timeseries
cognitedata/cognite-sdk-js pull request #284
Opened 2019-09-11 18:04 UTC by polomani

So basically those tests show the way Asset and Timeseries behave while shallow copied.
I am still not sure I did the right thing here.

I mean it just makes our code messier, while for the user it's just a matter of calling `toJSON()`.
or do something like `const {id, name} = asset; const partialAssetData = {id, name}`

So idk if we should be responsible for people destructing our classes in a poor way...

2019-09-11 20:49 UTC, ghost requested changes

2019-09-11 20:49 UTC, f1cognite commented on src/__tests__/resources/assetList.integration.specs.ts
> -  test('json stringify', async () => {
Why remove?

2019-09-11 20:49 UTC, f1cognite commented on src/__tests__/resources/assets.unit.spec.ts
> +    test('assets.list().autoPagingToArray()', async () => {
Not meaningful test description

2019-09-11 20:49 UTC, f1cognite commented on src/__tests__/resources/assets.unit.spec.ts
> +      expect(JSON.stringify(assets)).toBeTruthy();
`toBeTruthy` will I consider to be a weak test here. What do you test with that?

2019-09-11 20:49 UTC, f1cognite commented on src/__tests__/resources/assets.unit.spec.ts
> +      const shallowCopyItems: TypeAsset[] = [...assets, assets[0]];
This is not spreading any objects? Just spreading an array which already works fine...

2019-09-11 20:49 UTC, f1cognite commented on src/__tests__/resources/assets.unit.spec.ts
> +    test('assets.list()', async () => {
I don't see the need for this test? Duplicate of the one above? If we are using autoPaginate or not shouldn't matter or no?

2019-09-11 20:49 UTC, f1cognite commented on src/__tests__/resources/timeSeriesList.unit.spec.ts
> +    test('timeseries.list().autoPagingToArray()', async () => {
Bad test description. If this test fails what was the cause of the problem by looking at the logs?

2019-09-11 20:49 UTC, f1cognite commented on src/resources/classes/timeSeries.ts
> +    this.externalId = props.externalId;
We could potentially add support in `BaseResource` for a list of prop names like `['externalId', 'name', 'isString', ...]`. And then use that list to create the `toJSON` return value and we could send the props to `BaseResource` as before.

2019-09-12 08:11 UTC, polomani commented on src/resources/classes/timeSeries.ts
> +    this.externalId = props.externalId;
and the force casting to the type we need? 'cause we will lose the type information
also how will you able to remember to update that list of strings every time you update the interface?

2019-09-12 08:13 UTC, polomani commented on src/__tests__/resources/assets.unit.spec.ts
> +    test('assets.list()', async () => {
the one above returns `Asset[]`, but this one returns `AssetList`
bug?

2019-09-12 08:14 UTC, polomani commented on src/__tests__/resources/assets.unit.spec.ts
> +      const shallowCopyItems: TypeAsset[] = [...assets, assets[0]];
you are right, will remove it

2019-09-12 08:14 UTC, polomani commented on src/__tests__/resources/assets.unit.spec.ts
> +      expect(JSON.stringify(assets)).toBeTruthy();
basically just that it's not failing, maybe snapshot instead?

2019-09-12 08:15 UTC, polomani commented on src/__tests__/resources/assetList.integration.specs.ts
> -  test('json stringify', async () => {
moved to unit test intead

2019-09-14 13:02 UTC, ghost approved these changes

2019-09-14 13:02 UTC, ghost commented on src/__tests__/resources/assets.unit.spec.ts
> +        .thrice()
Why `thrice`? This runs before each and not before all

2019-09-14 13:02 UTC, ghost commented on src/__tests__/resources/assets.unit.spec.ts
> +      expect([{ ...result[0] }, { ...result[1] }]).toEqual(items);
Excellent!

2019-09-15 18:36 UTC, polomani commented on src/__tests__/resources/assets.unit.spec.ts
> +        .thrice()
one of tests requires 3 call, I didn't want to have a special case for that..

2019-09-16 13:38 UTC, merged

2019-09-16 13:47 UTC, polomani commented
:tada: This PR is included in version 2.3.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@cognite/sdk)
- [GitHub release](https://github.com/cognitedata/cognitesdk-js/releases/tag/v2.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: