Feat/datasets
cognitedata/cognite-sdk-js pull request #343
Opened 2020-02-07 13:31 UTC by polomani

2020-03-06 11:10 UTC, polomani commented on src/resources/datasets/datasetsApi.ts
> +    return super.deleteEndpoint(ids);
remove this

2020-03-11 07:27 UTC, hhenriques requested changes
Missing fields and a method on Datasets. @mrtraser here's the docs for the Datasets PR: https://pr-793.specs.preview.cogniteapp.com/v1.json.html#tag/Assets

2020-03-11 07:27 UTC, hhenriques commented on src/__tests__/resources/datasets.integration.spec.ts
> +  });
We're missing a test for `datasets/aggregate`

2020-03-11 07:27 UTC, hhenriques commented on src/resources/datasets/datasetsApi.ts
> +}
Missing `dataset/aggregate`

2020-03-11 07:27 UTC, hhenriques commented on src/resources/classes/asset.ts
> +    this.dataSetId = props.dataSetId;
`dataSetId` needs to be added to Events, Files and Sequences

2020-03-11 08:12 UTC, hhenriques approved these changes
Looks good!

2020-03-11 14:04 UTC, mrtraser approved these changes
LGTM, except linting ofc.

2020-03-11 14:21 UTC, merged