fix: add codeSnippets/ to .gitignore
cognitedata/cognite-sdk-js pull request #376
Opened 2020-06-19 08:31 UTC by haved

2020-06-19 10:30 UTC, polomani requested changes
LG, but this is not a fix (it doesn't require a new release), but rather a `chore`

2020-06-19 11:07 UTC, haved commented
I changed the title of the pr, is that sufficient if it's squash merged?

2020-06-19 11:55 UTC, polomani commented
@haved we can rename yes, but just for the future

2020-06-19 11:56 UTC, merged

2020-06-23 11:10 UTC, cognite-cicd commented
:tada: This PR is included in version 2.31.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@cognite/sdk/v/2.31.0)
- [GitHub release](https://github.com/cognitedata/cognite-sdk-js/releases/tag/v2.31.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: