docs(readme): best practices for imports
cognitedata/cognite-sdk-js pull request #384
Opened 2020-07-03 15:10 UTC by polomani

2020-07-08 07:31 UTC, hhenriques requested changes
A great addition to the documentation. Just suggest some minor changes to the wording

2020-07-08 07:31 UTC, hhenriques commented on README.md
> +We highly recommend avoid importing anything from internal sdk modules.
```suggestion
We highly recommend avoiding importing anything from internal SDK modules.
```

2020-07-08 07:31 UTC, hhenriques commented on README.md
> +You may leverage [eslint](https://eslint.org/docs/rules/no-restricted-imports) to free yourself from memorizing those rules:
```suggestion
We recommend the usage of [eslint](https://eslint.org/docs/rules/no-restricted-imports) to the ensure this best practice is enforced without having to memorize the patterns:
```

2020-07-14 11:33 UTC, polomani commented
We might need to rebase this on v3 branch

2020-07-22 07:39 UTC, polomani commented
A added this to v3 directly

2020-07-22 07:39 UTC, closed without merging