fix: Fix name of datasets ID scope in datasets ACLs
cognitedata/cognite-sdk-js pull request #447
Opened 2020-11-19 14:22 UTC by frxstrem

The name of the datasets ID scope should be `idScope`, `datasetScope` is not a valid name.

2020-11-19 14:41 UTC, polomani requested changes
`AclScopeDatasetsIds` is used in many places, for resource types ALCs, like here.

```
export type AclScopeEvents = AclScopeAll | AclScopeDatasetsIds;
```
so we need to create a separate type for this single case

2020-11-19 21:17 UTC, frxstrem commented
@polomani Nice catch, I wasn't aware that it was used for multiple ACLs in this way. I'll fix the PR to work around that.

Though I think that means that this problem is just a symptom of a different problem: that the "scope" values of different ACLs aren't really comparable types (i.e. `DatasetsAcl.Scope` has absolutely no relation to `EventsAcl.Scope` in the actual protobuf schema, even if they both may refer to a set of dataset IDs), so a union of types in this way isn't really the "correct" way to model it.

2020-11-20 08:29 UTC, polomani commented
need to fix this as well I believe?
```
export type AclScopeFiles = AclScopeAll | AclScopeDatasets;
```
to
```
export type AclScopeFiles = AclScopeAll | AclScopeDatasetsIds;
```

and squash & rename commit name to be the same format as pr title :)

2020-11-23 12:08 UTC, polomani approved these changes

2020-11-25 11:16 UTC, merged