fix: setting a field resolver to undefined [release]
cognitedata/cognite-sdk-js pull request #486
Opened 2021-02-15 15:24 UTC by Tapped

We should not auto wrap values that are undefined since a Constant Resolver with undefined value is not supported by the API. Instead we should just ignore undefined field resolvers.

2021-03-01 12:10 UTC, mrtraser requested changes

2021-03-01 12:10 UTC, mrtraser commented on packages/beta/src/api/templateGroups/templateInstancesApi.ts
> +        } else if (!this.isFieldResolver(fieldResolver)) {
```suggestion
        if (fieldResolver !==  undefined && !this.isFieldResolver(fieldResolver)) {
```

2021-03-01 12:10 UTC, mrtraser commented on packages/beta/src/api/templateGroups/templateInstancesApi.ts
> +          return [name, undefined];
```suggestion
```

2021-04-28 20:35 UTC, peternic approved these changes

2021-04-29 10:09 UTC, merged