chore: auth-wraper docs
cognitedata/cognite-sdk-js pull request #815
Opened 2022-06-03 07:58 UTC by devbarba

- Added auth-wrapper docs.

2022-07-01 13:08 UTC, sowmyaraj92 requested changes
@devbarba The review comments are fixed? There are a few places where we need more context and clarity, let me know when you're done making the changes.

2022-07-01 13:08 UTC, sowmyaraj92 commented on guides/auth-wrapper.md
> +​
Missing link

2022-07-01 13:08 UTC, sowmyaraj92 commented on guides/auth-wrapper.md
> +You can find a full sample application [here]()
Missing link

2022-07-01 13:08 UTC, sowmyaraj92 commented on guides/auth-wrapper.md
> +​
Missing link

2022-07-01 13:08 UTC, sowmyaraj92 commented on guides/auth-wrapper.md
> +​
Missing link

2022-07-01 13:08 UTC, sowmyaraj92 commented on guides/auth-wrapper.md
> +You can find a full sample application [here]()
Missing link

2022-07-01 13:08 UTC, sowmyaraj92 commented on guides/auth-wrapper.md
> +​
Missing link

2022-07-01 13:08 UTC, sowmyaraj92 commented on guides/auth-wrapper.md
> +​
Missing link

2022-07-01 13:08 UTC, sowmyaraj92 commented on guides/auth-wrapper.md
> +true to handle headers appropriately.
Unclear information - need more context here.

2022-07-01 13:08 UTC, sowmyaraj92 commented on guides/auth-wrapper.md
> +### getToken metod
metod > "method"

2022-07-01 13:08 UTC, sowmyaraj92 commented on guides/auth-wrapper.md
> +API keys use the same API in the SDK, using `credentials` you will need to set the following object to handle headers appropriately.
Same as the above comment.

2022-07-01 13:08 UTC, sowmyaraj92 commented on guides/auth-wrapper.md
> +​
Todo:- Will update the entire header in the next review commit!

2022-07-07 21:38 UTC, cognite-ornellas commented on guides/auth-wrapper.md
> +​
Is this resolved? Could not find it.

2022-07-07 21:38 UTC, cognite-ornellas commented on guides/auth-wrapper.md
> +You can find a full sample application [here]()
Is this resolved? Could not find it.

2022-07-07 21:38 UTC, cognite-ornellas commented on guides/auth-wrapper.md
> +​
Is this resolved? Could not find it.

2022-07-07 21:38 UTC, cognite-ornellas commented on guides/auth-wrapper.md
> +​
Is this resolved? Could not find it.

2022-07-07 21:38 UTC, cognite-ornellas commented on guides/auth-wrapper.md
> +You can find a full sample application [here]()
Is this resolved? Could not find it.

2022-07-08 13:48 UTC, sowmyaraj92 approved these changes
Just one minor change, otherwise we are good to merge! LGTM 🚀

2022-07-08 13:48 UTC, sowmyaraj92 commented on README.md
> +and the second is using [Microsoft MSAL Library](./guides/auth-wrapper.md)
```suggestion
We offer two ways to sign in to our SDK. The first and recommended approach is using [@cognite/auth-wrapper](./guides/auth-wrapper.md)
and the second is using [Microsoft MSAL Library](./guides/auth-wrapper.md)
```

2022-07-12 17:54 UTC, cognite-ornellas approved these changes

2022-07-13 20:17 UTC, merged